engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Metrics/CyclomaticComplexity:
        enabled: false
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.js"
  - "**.jsx"
  - "**.rb"
exclude_paths:
- config/**/*
- db/**/*
- spec/**/*
- vendor/**/*
