engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Metrics/CyclomaticComplexity:
        enabled: false
    exclude_fingerprints:
    - 1d05cd733d851f0fe43349c14e00e0ef
    - 7097b81d5e79fa8746fe3d2360512673
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false
    exclude_fingerprints:
    - c95e0c49c7ee402bb9e686d2b8058b30
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.js"
  - "**.jsx"
  - "**.rb"
exclude_paths:
- config/**/*
- db/**/*
- spec/**/*
- vendor/**/*
