# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f2b311a8b047cabd23e596d387db6ecb4fdbe2d93095ae9f939ac178a88eac2e216c131ac5c421edd0b198da49dccb0bf38b17e6ee62bbbfe666228ce881e2d
  gmail_email: "aceleradoratw9@gmail.com"
  gmail_password: "naomecalo"

test:
  secret_key_base: 43ca73951a120617b47d26a47f44d8aa612980c952b81605f4049bc3ce56096880d08992e8d9631c47849260a954efe6396786fac1ad31a6518f02cc4e08f856
  gmail_email: "aceleradoratw9@gmail.com"
  gmail_password: "naomecalo"
    # Do not keep production secrets in the repository,
    # instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
